"""Generate docs/THIRD_PARTY_LICENSES.md: Python packages (pip-licenses), models, fonts.

Usage: python scripts/license_report.py [--out docs/THIRD_PARTY_LICENSES.md]
       python scripts/license_report.py --register [--out docs/LICENSES.md]

--register writes the G-LIC-1 register: the generated tables plus benchmark fonts and the
curated datasets and planned components from tools/license_register.yaml.

Run it inside the project venv with the extras you ship installed; pip-licenses (dev
extra) reads the installed distributions. Copyleft, non-commercial, proprietary and
unknown licences are flagged.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import yaml

from manga_ar import __version__
from manga_ar.models.registry import REGISTRY
from manga_ar.typeset.fonts import VENDORED

ROOT = Path(__file__).resolve().parents[1]
SELF = {"manga-arabic-translator"}


def classify(license_text: str, name: str = "") -> str:
    """Category from the short licence name (never the full text: "COMPLIANCE" contains
    "MPL"). NVIDIA's CUDA wheels report UNKNOWN or proprietary licences."""
    t = short(license_text).upper()
    if name.lower().startswith(("nvidia-", "cuda-toolkit")):
        return "PROPRIETARY (redistributable EULA)"
    if "PROPRIETARY" in t or "NVIDIA" in t:
        return "PROPRIETARY (redistributable EULA)"
    if "AGPL" in t:
        return "STRONG COPYLEFT"
    if "LGPL" in t or "LESSER GENERAL" in t or "LIBRARY OR LESSER" in t:
        return "weak copyleft (LGPL)"
    if "GPL" in t or "GENERAL PUBLIC" in t:
        return "STRONG COPYLEFT"
    if "MPL" in t or "MOZILLA" in t:
        return "weak copyleft (MPL, file-level)"
    if "-NC" in t or "NON-COMMERCIAL" in t or "NONCOMMERCIAL" in t:
        return "NON-COMMERCIAL"
    if "UNKNOWN" in t or not t.strip():
        return "unknown: check"
    return "permissive"


def short(license_text: str) -> str:
    first = license_text.strip().splitlines()[0] if license_text.strip() else "UNKNOWN"
    if first.startswith("Apache License") or first.startswith("Apache Software"):
        return "Apache-2.0"
    return first[:70]


def packages() -> list[dict[str, str]]:
    out = subprocess.run(
        [sys.executable, "-m", "piplicenses", "--format=json", "--with-urls"],
        capture_output=True,
        text=True,
        check=True,
    )
    rows = [r for r in json.loads(out.stdout) if r["Name"] not in SELF]
    return sorted(rows, key=lambda r: r["Name"].lower())


def package_lines(rows: list[dict[str, str]]) -> list[str]:
    lines = ["| Package | Version | Licence | Category |", "|---|---|---|---|"]
    for r in rows:
        cat = classify(r["License"], r["Name"])
        mark = f"**{cat}**" if cat != "permissive" else cat
        lines.append(f"| {r['Name']} | {r['Version']} | {short(r['License'])} | {mark} |")
    return lines


def model_lines() -> list[str]:
    lines = ["| Name | Licence | Flag | Description |", "|---|---|---|---|"]
    for spec in REGISTRY.values():
        flag = "**copyleft/NC: opt-in**" if spec.copyleft_or_nc else "—"
        lines.append(f"| {spec.name} | {spec.license} | {flag} | {spec.description} |")
    return lines


def font_lines() -> list[str]:
    lines = ["| Key | File | Family | Licence |", "|---|---|---|---|"]
    for key, (filename, family, lic, _role) in VENDORED.items():
        lines.append(f"| {key} | {filename} | {family} | {lic} |")
    return lines


def bench_font_lines() -> list[str]:
    if str(ROOT) not in sys.path:  # `benchmarks` is a repo package, not an installed one
        sys.path.insert(0, str(ROOT))
    from benchmarks.generators.fonts import FONTS

    lines = ["| Key | File | Licence | SHA-256 |", "|---|---|---|---|"]
    for key, spec in FONTS.items():
        lines.append(f"| {key} | {spec.filename} | {spec.license} | `{spec.sha256[:16]}…` |")
    return lines


def curated_lines(entries: list[dict[str, str]]) -> list[str]:
    lines = ["| Name | Licence | Redistribution | Flag | Use |", "|---|---|---|---|---|"]
    for e in entries:
        flag = e["flag"] if e["flag"] == "none" else f"**{e['flag']}**"
        lines.append(f"| {e['name']} | {e['license']} | {e['redistribution']} | {flag} | "
                     f"{e['use']} |")  # fmt: skip
    return lines


def register(rows: list[dict[str, str]]) -> list[str]:
    curated = yaml.safe_load((ROOT / "tools" / "license_register.yaml").read_text("utf-8"))
    flagged = [r for r in rows if classify(r["License"], r["Name"]) != "permissive"]
    return [
        "# Licence register (G-LIC-1)",
        "",
        f"Generated by `scripts/license_report.py --register` on {date.today().isoformat()}"
        " from the build environment and `tools/license_register.yaml`. Every model, font, "
        "dataset and dependency is recorded here, with its licence and redistribution "
        "status, before use (PD-8). Non-commercial, copyleft, proprietary and unverified "
        "items are flagged. MangaAR's own code is MIT-licensed. Obligations: "
        "`docs/THIRD_PARTY_LICENSES.md`.",
        "",
        "## Datasets",
        "",
        *curated_lines(curated["datasets"]),
        "",
        "## Planned Phase 1 components (recorded before use; none installed yet)",
        "",
        *curated_lines(curated["planned"]),
        "",
        "## Runtime models (downloaded on demand into the cache; never committed)",
        "",
        *model_lines(),
        "",
        "## Bundled fonts (`src/manga_ar/assets/fonts/`, licence texts included)",
        "",
        *font_lines(),
        "",
        "## Benchmark generator fonts (downloaded with pinned SHA-256; never committed)",
        "",
        *bench_font_lines(),
        "",
        f"## Python packages ({len(rows)} installed, {len(flagged)} flagged)",
        "",
        *package_lines(rows),
        "",
    ]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--register", action="store_true", help="write docs/LICENSES.md")
    args = ap.parse_args(argv)
    rows = packages()
    if args.register:
        out = args.out or ROOT / "docs" / "LICENSES.md"
        out.write_text("\n".join(register(rows)), encoding="utf-8")
        sys.stdout.write(f"wrote {out}\n")
        return 0
    args.out = args.out or ROOT / "docs" / "THIRD_PARTY_LICENSES.md"
    flagged = [r for r in rows if classify(r["License"], r["Name"]) != "permissive"]
    lines = [
        "# Third-party licences",
        "",
        f"Generated by `scripts/license_report.py` for MangaAR {__version__} on "
        f"{date.today().isoformat()} from the build environment (all extras installed: "
        "rapid, ocr, lama, manga, gui, dev). MangaAR's own code is MIT-licensed.",
        "",
        "## Summary of obligations and flags",
        "",
        "- **python-bidi (LGPL-3.0)**: a core dependency, used unmodified as a separate "
        "library (imported, not vendored or changed). This is compatible with MIT "
        "distribution; if you ship a frozen bundle (PyInstaller), keep it replaceable "
        "and include the LGPL text.",
        "- **MPL-2.0 (certifi, tqdm, orjson, hypothesis, pathspec)**: file-level weak "
        "copyleft, used unmodified. No obligation beyond keeping the notices.",
        "- **NVIDIA CUDA runtime libraries (proprietary, redistributable EULA)**: on "
        "Linux, the default PyPI `torch` wheel depends on `nvidia-*` / `cuda-toolkit` "
        "packages. They are pulled only by the optional extras that need torch (`ocr`, "
        "`lama`, `manga`, `offline-mt`), never by the core, `rapid` or `gui`. For a "
        "fully open-source install, install the CPU build of torch first: "
        "`pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu`, "
        'then `pip install -e ".[ocr,lama,gui]"`. Windows and macOS PyPI wheels do '
        "not include them.",
        "- **comic-text-detector weights (GPL-3.0)**: opt-in only (`--detector ctd`), "
        "never downloaded by default. The ONNX file is downloaded into the user's cache, "
        "not distributed by MangaAR.",
        "- **OPUS-MT Marian models (CC-BY-4.0)**: offline translation (`models download "
        "local-mt`). Attribution to the Helsinki-NLP / OPUS-MT project is required when "
        "you publish translations made with them.",
        "- **NLLB (CC-BY-NC-4.0)**: deliberately **not used** (non-commercial).",
        "- **Fonts**: all bundled fonts are SIL OFL-1.1; licence texts ship in "
        "`src/manga_ar/assets/fonts/licenses/`.",
        "",
        f"## Python packages ({len(rows)} installed, {len(flagged)} flagged)",
        "",
        *package_lines(rows),
    ]
    lines += [
        "",
        "## Models (downloaded on demand into the cache; none are committed or bundled)",
        "",
        *model_lines(),
    ]
    lines += [
        "",
        "## Bundled fonts (`src/manga_ar/assets/fonts/`)",
        "",
        *font_lines(),
    ]
    lines += [
        "",
        "Font SHA-256 checksums: `src/manga_ar/assets/fonts/SHA256SUMS`. CJK fixture "
        "fonts (Noto Sans JP/KR/SC subsets, OFL-1.1) are downloaded by "
        "`manga-arabic models download fonts`, never committed.",
        "",
    ]
    args.out.write_text("\n".join(lines), encoding="utf-8")
    sys.stdout.write(f"wrote {args.out} ({len(rows)} packages, {len(flagged)} flagged)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
