"""Generate docs/THIRD_PARTY_LICENSES.md: Python packages (pip-licenses), models, fonts.

Usage: python scripts/license_report.py [--out docs/THIRD_PARTY_LICENSES.md]

Run it inside the project venv with the extras you ship installed; pip-licenses (dev
extra) reads the installed distributions. Copyleft, non-commercial, proprietary and
unknown licences are flagged.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

from manga_ar import __version__
from manga_ar.models.registry import REGISTRY
from manga_ar.typeset.fonts import VENDORED

ROOT = Path(__file__).resolve().parents[1]
SELF = {"manga-arabic-translator"}


def classify(license_text: str, name: str = "") -> str:
    """Category from the short licence name (never the full text: "COMPLIANCE" contains
    "MPL"). NVIDIA's CUDA wheels report UNKNOWN or proprietary licences."""
    t = short(license_text).upper()
    if name.lower().startswith(("nvidia-", "cuda-toolkit")):
        return "PROPRIETARY (redistributable EULA)"
    if "PROPRIETARY" in t or "NVIDIA" in t:
        return "PROPRIETARY (redistributable EULA)"
    if "AGPL" in t:
        return "STRONG COPYLEFT"
    if "LGPL" in t or "LESSER GENERAL" in t or "LIBRARY OR LESSER" in t:
        return "weak copyleft (LGPL)"
    if "GPL" in t or "GENERAL PUBLIC" in t:
        return "STRONG COPYLEFT"
    if "MPL" in t or "MOZILLA" in t:
        return "weak copyleft (MPL, file-level)"
    if "-NC" in t or "NON-COMMERCIAL" in t or "NONCOMMERCIAL" in t:
        return "NON-COMMERCIAL"
    if "UNKNOWN" in t or not t.strip():
        return "unknown: check"
    return "permissive"


def short(license_text: str) -> str:
    first = license_text.strip().splitlines()[0] if license_text.strip() else "UNKNOWN"
    if first.startswith("Apache License") or first.startswith("Apache Software"):
        return "Apache-2.0"
    return first[:70]


def packages() -> list[dict[str, str]]:
    out = subprocess.run(
        [sys.executable, "-m", "piplicenses", "--format=json", "--with-urls"],
        capture_output=True,
        text=True,
        check=True,
    )
    rows = [r for r in json.loads(out.stdout) if r["Name"] not in SELF]
    return sorted(rows, key=lambda r: r["Name"].lower())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=ROOT / "docs" / "THIRD_PARTY_LICENSES.md")
    args = ap.parse_args(argv)
    rows = packages()
    flagged = [r for r in rows if classify(r["License"], r["Name"]) != "permissive"]
    lines = [
        "# Third-party licences",
        "",
        f"Generated by `scripts/license_report.py` for MangaAR {__version__} on "
        f"{date.today().isoformat()} from the build environment (all extras installed: "
        "rapid, ocr, lama, manga, gui, dev). MangaAR's own code is MIT-licensed.",
        "",
        "## Summary of obligations and flags",
        "",
        "- **python-bidi (LGPL-3.0)**: a core dependency, used unmodified as a separate "
        "library (imported, not vendored or changed). This is compatible with MIT "
        "distribution; if you ship a frozen bundle (PyInstaller), keep it replaceable "
        "and include the LGPL text.",
        "- **MPL-2.0 (certifi, tqdm, orjson, hypothesis, pathspec)**: file-level weak "
        "copyleft, used unmodified. No obligation beyond keeping the notices.",
        "- **NVIDIA CUDA runtime libraries (proprietary, redistributable EULA)**: on "
        "Linux, the default PyPI `torch` wheel depends on `nvidia-*` / `cuda-toolkit` "
        "packages. They are pulled only by the optional extras that need torch (`ocr`, "
        "`lama`, `manga`, `offline-mt`), never by the core, `rapid` or `gui`. For a "
        "fully open-source install, install the CPU build of torch first: "
        "`pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu`, "
        'then `pip install -e ".[ocr,lama,gui]"`. Windows and macOS PyPI wheels do '
        "not include them.",
        "- **comic-text-detector weights (GPL-3.0)**: opt-in only (`--detector ctd`), "
        "never downloaded by default. The ONNX file is downloaded into the user's cache, "
        "not distributed by MangaAR.",
        "- **OPUS-MT Marian models (CC-BY-4.0)**: offline translation (`models download "
        "local-mt`). Attribution to the Helsinki-NLP / OPUS-MT project is required when "
        "you publish translations made with them.",
        "- **NLLB (CC-BY-NC-4.0)**: deliberately **not used** (non-commercial).",
        "- **Fonts**: all bundled fonts are SIL OFL-1.1; licence texts ship in "
        "`src/manga_ar/assets/fonts/licenses/`.",
        "",
        f"## Python packages ({len(rows)} installed, {len(flagged)} flagged)",
        "",
        "| Package | Version | Licence | Category |",
        "|---|---|---|---|",
    ]
    for r in rows:
        cat = classify(r["License"], r["Name"])
        mark = f"**{cat}**" if cat != "permissive" else cat
        lines.append(f"| {r['Name']} | {r['Version']} | {short(r['License'])} | {mark} |")
    lines += [
        "",
        "## Models (downloaded on demand into the cache; none are committed or bundled)",
        "",
        "| Name | Licence | Flag | Description |",
        "|---|---|---|---|",
    ]
    for spec in REGISTRY.values():
        flag = "**copyleft/NC: opt-in**" if spec.copyleft_or_nc else "—"
        lines.append(f"| {spec.name} | {spec.license} | {flag} | {spec.description} |")
    lines += [
        "",
        "## Bundled fonts (`src/manga_ar/assets/fonts/`)",
        "",
        "| Key | File | Family | Licence |",
        "|---|---|---|---|",
    ]
    for key, (filename, family, lic, _role) in VENDORED.items():
        lines.append(f"| {key} | {filename} | {family} | {lic} |")
    lines += [
        "",
        "Font SHA-256 checksums: `src/manga_ar/assets/fonts/SHA256SUMS`. CJK fixture "
        "fonts (Noto Sans JP/KR/SC subsets, OFL-1.1) are downloaded by "
        "`manga-arabic models download fonts`, never committed.",
        "",
    ]
    args.out.write_text("\n".join(lines), encoding="utf-8")
    sys.stdout.write(f"wrote {args.out} ({len(rows)} packages, {len(flagged)} flagged)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
